# Site
name: 'Spiritual Geek'
description: 'Technology | Mythology | Culture | Life Science'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'spiritual-geek'
email: 'swapnil_kulkarni@outlook.com'
mailchimp-list: 'https://github.us19.list-manage.com/subscribe/post?u=5fa1e3b68bbade2285da4ad24&amp;id=7cb3d87d04'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    swapnil:
      name:           Swapnil
      site:           https://spiritual-geek.github.io
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Swapnil Kulkarni, the author of Spiritual Geek, I hope you like it!"
      email:          swapnil_kulkarni@outlook.com
      twitter:        https://twitter.com/swapnilkul

    smruti:
      name:           smruti
      site:           https://spiritual-geek.github.io
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: swapnil
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
