# Site
name: 'Spiritual Geek'
description: 'Technology | Mythology | Culture | Life Science'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'spiritual-geek'
email: 'swapnil_kulkarni@outlook.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    swapnil:
      name:           Swapnil Vivek Kulkarni
      site:           spiritual-geek.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Software Professional, Tech Enthusiast, Nationalist, Proud Indian"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/swapnilkul

    smruti:
      name:           Smruti Prayag
      site:           spiritual-geek.github.io
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          kulsmru@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
